on:
  push:
    branches:
      - master
  pull_request:
name: CI
jobs:
  packages:
    name: Package sanity tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # No shallow clone, we need all history!
      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
      - name: Install Hermit
        run: |
          set -e
          set -o pipefail
          curl -fsSL https://github.com/cashapp/hermit/releases/download/stable/install.sh | bash
      - name: Test packages
        run: |
          set -x
          mkdir build testenv
          ~/bin/hermit validate "file://$PWD"
          ~/bin/hermit init --sources="file://$PWD" ./testenv
          . ./testenv/bin/activate-hermit
          git diff --name-only '${{ github.event.before }}..${{ github.event.after }}' | fgrep .hcl | cut -d. -f1 | xargs -n1 hermit search -s | grep -v -E '@latest|@[0-9]' | xargs -n1 hermit test --level=debug
